apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic
    app.kubernetes.io/part-of: load-app-aff7faf5-b7d8-4dd2-9ad2-56d03235d5ae
  name: devfile-sample-python-basic
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/test-rhtap-1-tenant/load-app-aff7faf5-b7d8-4dd2-9ad2-56d03235d5ae/devfile-sample-python-basic@sha256:6a82a67c764616ec51f8b86838d4094bc72221ebc86045d933454f785ce7a863
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
